### ISSUE TITLE
introduce config option to clean all named sections in Manifest.MF

### ISSUE THREAD

**Issue by tobit800** [tschulte/gradle-jnlp-plugin#34]
Hello Tobias!

I use your plugin in my Java WebStart project. Thanks a lot for your work!

Today I have problems with the MANIFEST in one special jar:
http://search.maven.org/#artifactdetails|commons-httpclient|commons-httpclient|3.1|jar

The problem is line 7: "Name: org/apache...". This leads to a verification-error in the WebStart-client.
Could you please try to reproduce the problem and give me any hint how to
handle this? I already tried:
  
  signJarRemovedManifestEntries = '(?:Trusted-Only|Trusted-Library|.*-Digest|Name|Build-By)'

but this does not help.

Thanks a lot in advance,
Tobias Otto

**Comment by tschulte** [comment]
I could not reproduce this with Java 8u91 on Linuxmint. But we have some problems with newer Java versions as well. When starting our application, we get a couple of security warnings. Can you please try starting the application using the newest early access version of Java (https://jdk8.java.net/download.html)? Our problems went away with this version (which should get released soon).

**Comment by tobit800** [comment]
Hi Tobias

I found a solution that works for me. I remove the additional Manifest-Entries with one new line in your class **SingJarsTask** in method `File copyUnsignAndAlterManifest(File input)` I added:
`manifest.getEntries().clear()`

This removes my problem and I am happy, because it already took too much time to solve this.

Thanks a lot for your help,
Tobias Otto

**Comment by tschulte** [comment]
This is a bug in Javaws https://bugs.openjdk.java.net/browse/JDK-8156682. Although, we might still want to add a feature to the plugin to remove arbitrary manifest entries.

**Comment by tschulte** [comment]
setting signJarRemovedManifestEntries to "(?!Manifest-Version|Signature-Version).*" should also do the trick.

**Comment by tschulte** [comment]
No, it does not. The problem is that `Name: ` starts a new individual section (http://docs.oracle.com/javase/8/docs/technotes/guides/jar/jar.html#Manifest_Specification). The individual sections are also used during signing the jar. But webstart seems to have issues with individual sections without signing information. Currently there is no way in the plugin to get rid of these entries.

I think I will have to change the plugin by introducing a new switch to clear all individual sections. Additionally, all individual sections that are empty after cleanup should be removed.

**Comment by tschulte** [comment]
Added new config option `signJarRemovedNamedManifestEntries`. When setting this option to `.*`, all named attributes will be cleared.
