### ISSUE TITLE
Support query string in href

### ISSUE THREAD

**Issue by mauromol** [tschulte/gradle-jnlp-plugin#43]
Right now, when using this:

```groovy
jnlp {
  href 'start.jnlp'
}
```

you change both the name of the generated JNLP file and the contents of the `href` attribute of the generated `jnlp` element.

But I need to add a query string to the `href` attribute value. This requires me to implement some post-processing to the result of `JnlpDownloadServlet` through a filter to add the missing query string at runtime.

**Comment by tschulte** [comment]
Please also see my response to #45. If you use the jnlp-war plugin, the jnlp file is changed to use `$$name` and `$$href` instead of the static href. Is that sufficient?

**Comment by mauromol** [comment]
> Is that sufficient?

Now that you have explained about the `jnlp-war` plugin, it's interesting indeed. But I think it would be nice if the `jnlp` plugin by itself could separate the concept of the generated jnlp file name and the `href` value. Indeed, I'm currently using the default `JnlpDownloadServlet` in JDK sample code and `$$codebase` variable in the JNLP generated by the jnlp plugin, but I can't use `$$href` for the `jnlp` element `href` attribute value. I looked at the code and I think it should be rather simple to split the two concepts, by adding something like a `jnlp.jnlpFileName` property and making the `href` default value equal to this property value.

**Comment by tschulte** [comment]
You can always do that with

```groovy
tasks.generateJnlp.doLast {
    jnlpFile.text = jnlpFile.text.replace(jnlpFile.name, '$$href')
}
```

But you will have problems because of the two lines 

```
    <property name='jnlp.versionEnabled' value='true' />
    <property name='jnlp.packEnabled' value='true' />
```

because in that case the webstart client will not use the jnlp download protocol.

**Comment by mauromol** [comment]
> You can always do that with
>```
>tasks.generateJnlp.doLast {
>    jnlpFile.text = jnlpFile.text.replace(jnlpFile.name, '$$href')
>}
>```

Nice hint, I will evaluate this instead of my solution. Indeed, I have to post-process the JNLP file at runtime in any case because I need to replace other (custom) variables depending on the query string contents.

>But you will have problems because of the two lines
>```
>    <property name='jnlp.versionEnabled' value='true' />
>    <property name='jnlp.packEnabled' value='true' />
>```
>
>because in that case the webstart client will not use the jnlp download protocol.

This is not clear, instead. What's the relationship between the presence of these elements (and hence the download protocol in use) and the `$$href` replacement made by the JnlpDownloadServlet? Shouldn't they be independent from each other?

**Comment by tschulte** [comment]
Please have a look at http://docs.oracle.com/javase/8/docs/technotes/guides/jweb/index.html.

When you don't want to use the jnlp-war plugin and the plugins own jnlp servlet, you will have to do some post processing of the jnlp file. `jnlp.versionEnabled` and `jnlp.packEnabled` are meant to be used without the servlet. The only think you cannot get without the servlet is jardiff and replacement of variables. If the only thing you need is replacement of the codebase, you could also create your own simple servlet to only do that. Otherwise I strongly suggest you try the jnlp-war plugin.

In all cases you should check with e.g. Wireshark the actual communication. When I have a jnlp file

```
<?xml version='1.0' encoding='UTF-8'?>
<jnlp spec='7.0' href='launch.jnlp' codebase='http://localhost:8080/war'>
  <information>
    <title>jnlp</title>
    <vendor>jnlp</vendor>
  </information>
  <resources>
    <j2se version='1.8' />
    <jar href='lib/jnlp.jar' version='1.0.0' main='true' />
    <property name='jnlp.versionEnabled' value='true' />
    <property name='jnlp.packEnabled' value='true' />
  </resources>
  <application-desc main-class='de.gliderpilot.jnlp.sample.Main' />
</jnlp>
```

And use the jnlp servlet as provided by the jdk, the following will happen:

* Download of the jnlp file by the browser
* Download again of the jnlp file, this time by the webstart client.
* Download attempt for lib/jnlp__V1.0.0.jar.pack.gz
  * jnlp.versionsEnabled instructs the client to add __V${version} to the url
  * jnlp.packEnabled instructs the client to add .pack.gz to the url
  * (results in HTTP 404)
* Download attempt for lib/jnlp.jar?version-id=1.0.0
* The above is repeated for every jar file

When using the jnlp-war plugin, the two properties are not present in the jnlp and therefore only one request is done for each jar.

**Comment by tschulte** [comment]
By using the jnlp-war plugin, there is no need to do that manually. If you don't want to use the jnlp-war plugin, you can use the workaround.

**Comment by mauromol** [comment]
I will do some tests. However, with the default `JnlpDownloadServlet` I observed that using `$$href` looses the query string part. See also http://bugs.java.com/bugdatabase/view_bug.do;jsessionid=905f5331b092524b502a35ced512b?bug_id=6654926
