### ISSUE TITLE
Gradle 7 incompability

### ISSUE THREAD

**Issue by tanmatra** [tschulte/gradle-jnlp-plugin#58]
Build error is
```
An exception occurred applying plugin request [id: 'org.gradle.java']
> Failed to apply plugin 'org.gradle.java'.
   > Could not get unknown property 'runtime' for configuration container of type org.gradle.api.internal.artifacts.configurations.DefaultConfigurationContainer.
```

Problem is in de.gliderpilot.gradle.jnlp.GradleJnlpPlugin.groovy, line 50:
```
project.configurations.jnlp.extendsFrom project.configurations.runtime
```

`runtime` configuration is now outdated in Gradle 7, it's possibly should be used `implementation` instead

**Comment by tschulte** [comment]
Using `implementation` instead does not seem right. We also need `runtimeOnly`. And it is not clear to me, if `runtimeOnly` extends from `implementation`.

But I would really rather have the integration tests catch this error first. But the used version of nebula-test does not support gradle 7. I know from experience, that updating that version, will cost some time. And releasing a new version might also not work directly, because I had to switch to travis.com. 

I also checked, when removing line 50 completely, no test at all fails. That should be fixed as well, to check if the desired behavior is still correct.

That being said, and taking into account that Java Webstart is dead as in The Walking Dead, and I have no idea if this plugin also works with Open-Webstart, I am not sure I want to invest that time. If this issue gets a couple of votes, I might reconsider it.

**Comment by amake** [comment]
Thanks for making this fix.

I was going to be happy sitting on Gradle 6.9 forever, but I just ran into this annoyance:

NetBeans 12.4 just came out. It uses Gradle 7.0 by default. It's *supposed to* be able to use your project's `gradlew` but in practice it chokes on loading a project if it doesn't at least compile with Gradle 7.0. This plugin is currently preventing that.

**Comment by tschulte** [comment]
I could not create the release yet. JCenter is now read-only. No new packages can be published to JCenter and all Bintray services have been shut down. I can not just release the plugin to the gradle plugin portal, since the jnlp-war plugin defines a dependency to
de.gliderpilot.gradle.jnlp:jnlp-servlet. I might need to learn how to deploy to mavenCentral() first.

**Comment by amake** [comment]
Sure, that's a big annoyance a lot of us dealt with recently.

I migrated all of my projects to [Sonatype OSSRH](https://central.sonatype.org/publish/publish-guide/) which syncs to Maven Central. The procedure is not too bad:

1. Open a JIRA ticket
2. Prove ownership of your various accounts (`gliderpilot.de` domain and your Bintray account, but I don't know how the latter will work now that Bintray is down)
3. Make a GPG key if you don't already have one
4. Update your Gradle files ([example 1](https://github.com/amake/TinyLisp/commit/b8a964f9f86d395edb3c289e95500ee777aaf3ae), [example 2](https://github.com/amake/SuperTMXMerge/compare/28469c1cbbe7538e658f931e8df4affcb685b0b2...8afa0f1e3c242470ec4aefa8a70ea888b158888e), [example 3](https://github.com/omegat-org/omegat/commit/5cafba9f61e4c4eea8ea1ff070d7e683f53e59f8))
5. Publish

**Comment by mauromol** [comment]
Please, please, reconsider this...

> Using `implementation` instead does not seem right. We also need `runtimeOnly`. And it is not clear to me, if `runtimeOnly` extends from `implementation`.

Perhaps the configuration you need to use is `runtimeClasspath`: https://docs.gradle.org/current/userguide/java_plugin.html#tab:configurations
This is a read-only configuration that can be used to gather all runtime dependencies, while it's not possible to add dependencies directly into it (you must use `implementation` or `runtimeOnly`, `runtimeClasspath` extends both).

> That being said, and taking into account that Java Webstart is dead as in The Walking Dead, and I have no idea if this plugin also works with Open-Webstart, I am not sure I want to invest that time. If this issue gets a couple of votes, I might reconsider it.

I haven't tested myself yet, but considering that the JNLP as a protocol is still the same and OpenWebStart is just another JNLP client implementation, I don't see why it shouldn't work with the JNLP produced by your plugin. Clearly, OpenWebStart has been designed to be compatible with Java Web Start as much as possible.
