### ISSUE TITLE
Add file to CopyJarsTask

### ISSUE THREAD

**Issue by ilsaul** [tschulte/gradle-jnlp-plugin#7]
Hi,
how can I add file i want to copy?

thanks

**Comment by tschulte** [comment]
CopyJarsTask is only used when not signing the jars, SignJarsTask otherwise. Both tasks are only meant to process the jars.

I don't understand what you want to do. But if you want to copy resources like html files or pngs, you should create a new task to copy these and let createWebstartDir depend on it.

**Comment by ilsaul** [comment]
Hi,
I have my jar signed in a folder and I want to insert they in the jnlp without sign they again.
An other question is I have a multi-project project and I want to provide all my jar to your createWebstartDir, how to let it understand where they are?

thanks

**Comment by tschulte** [comment]
If you have all jars already signed, just don't use define signJarParams. Having a mixed layout with some jars already signed and others not signed is not supported. I can think of ways to achive what you might want. But I have not fully understand what problem you have exactly. Can you give a minimal workable example?
